Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get '/list', to: 'home#list'

  scope '/page' do
    ### statics
    get '/home_owners', to: 'page#home_owners'
    get '/eligibility_sell', to: 'page#eligibility_sell'
    get '/eligibility_rent', to: 'page#eligibility_rent'
    get '/eligibility_buy', to: 'page#eligibility_buy'
    get '/eligibility_to_rent', to: 'page#eligibility_to_rent'
    get '/law_firms', to: 'page#law_firms'
    get '/bankers_contacts', to: 'page#bankers_contacts'
  end

  # get '/dashboard/listings', to: 'users/listings#index'

  resources :listings, only: [:index, :show]

  # signed in user
  resource :user, only: [:edit, :update] do
    resources :listings, :controller => 'users/listings', only: [:index, :new, :edit, :update, :show] do
      member do
        get 'preview'
        patch 'publish'
      end
      collection do
        post 'create_a_sell'
        post 'create_a_rent'
      end
      resources :photos, :controller => 'users/listings/photos', only: [:index, :create, :destroy] do
        collection do
          post 'sort'
        end
      end
    end
    
    resources :saved_listings, :controller => 'users/saved_listings', only: [:index, :create, :destroy]
    resources :messages, :controller => 'users/messages', only: [:index]

  end


  # Devise generated user_confirmation_url() looks something like below
  #   "https://.../users/confirmation.16?confirmation_token=Q5Qx2hZtv4WX6rsnXMYT"
  # where ".16" above is the new user id created.
  # When user clicks above link in his email, an exception occurs that says UnknownFormat.
  # So, instead of using user_confirmation_url() in confirmation_instructions.html.erb, we replace user_confirmation_url()
  # with below named path whose output is almost same as that of user_confirmation_url(), the key diff
  # being the piece of ".newUserId" preceding "?" is absent.
  # Notice our named path ends with query string "dummy=toAbsorbNewUserId".
  # Without this query string that follows query string "confirmation_token", the piece of ".newUserId"
  # generated by routes gets appended to confirmation_token.
  # This will generate invalid confirmation_token wheh user clicks on link in his email.
  # So, instead of looking like "https://.../users/confirmation?confirmation_token=ZzUNpxq11j57Vu87i_Wx.16&amp;dummy=toAbsorbNewUserId",
  # it should be like "https://.../users/confirmation?confirmation_token=ZzUNpxq11j57Vu87i_Wx&amp;dummy=toAbsorbNewUserId.16"
  ## get "#{AppConfig['relative_url_root']}/users/confirmation?confirmation_token=:confirmation_token&dummy=toAbsorbNewUserId", to: 'devise/confirmations#show', as: :user_confirm
  get "/users/confirmation?confirmation_token=:confirmation_token&dummy=toAbsorbNewUserId", to: 'devise/confirmations#show', as: :user_confirm

  # devise_for :users
  devise_for :users, :controllers => { registrations: 'devise/users/registrations', sessions: 'devise/users/sessions', passwords: 'devise/users/passwords' }
end
